esphome:
  name: ap33772s-d1-mini
  friendly_name: AP33772S D1 Mini

esp8266:
  board: d1_mini

logger:
  deassert_rts_dtr: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

api:

ota:
  platform: esphome

external_components:
  - source:
      type: local
      path: ../components
    components: [ap33772s]

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

ap33772s:
  id: ap33772s_hub
  address: 0x52
  target_profiles:
    - voltage: 20.0
    - voltage: 12.0
    - voltage: 5.0

binary_sensor:
  - platform: ap33772s
    ap33772s_id: ap33772s_hub
    pd_connected:
      name: "AP33772S PD Connected"

sensor:
  - platform: ap33772s
    ap33772s_id: ap33772s_hub
    voltage:
      name: "AP33772S Voltage"
    current:
      name: "AP33772S Current"
    temperature:
      name: "AP33772S Temperature"
    voltage_requested:
      name: "AP33772S Requested Voltage"
    current_requested:
      name: "AP33772S Requested Current"
