esphome:
  name: ap33772s-component-example
  friendly_name: AP33772S Component Example
  on_boot:
    then:
      - delay: 5s
      - request_power_profile:
          voltage: 9.0

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

external_components:
  - source:
      type: local
      path: ../components
    components: [ap33772s]

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

ap33772s:
  id: ap33772s_hub
  address: 0x52
  target_profiles:
    - voltage: 20.0
    - voltage: 12.0
    - voltage: 5.0
  keep_alive_interval: 500ms
  on_pd_negotiation_success:
    - logger.log: "PD negotiation succeeded!"
  on_pd_negotiation_failure:
    - logger.log: "PD negotiation failed"
  on_new_pdo:
    - logger.log: "New source capabilities detected"

binary_sensor:
  - platform: ap33772s
    ap33772s_id: ap33772s_hub
    pd_connected:
      name: "AP33772S PD Connected"
    fault_otp:
      name: "AP33772S OTP Fault"
    fault_ocp:
      name: "AP33772S OCP Fault"
    fault_ovp:
      name: "AP33772S OVP Fault"
    fault_uvp:
      name: "AP33772S UVP Fault"
    derating:
      name: "AP33772S Derating"

sensor:
  - platform: ap33772s
    ap33772s_id: ap33772s_hub
    voltage:
      name: "AP33772S Voltage"
    current:
      name: "AP33772S Current"
    temperature:
      name: "AP33772S Temperature"
    voltage_requested:
      name: "AP33772S Requested Voltage"
    current_requested:
      name: "AP33772S Requested Current"


